name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install global dependencies
        run: |
          npm install --global yarn
          git config --global user.email "ci@example.com"
          git config --global user.name "CI"

      # Core project
      - name: Get core yarn cache directory path
        id: core-yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache core yarn cache
        uses: actions/cache@v3
        id: core-yarn-cache
        with:
          path: ${{ steps.core-yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-core-${{ hashFiles('core/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-core-

      - name: Install dependencies in core
        run: |
          cd core
          HUSKY=0 yarn install --frozen-lockfile

      - name: Run lint in core
        run: |
          cd core
          yarn run lint